full ci test

diff --git a/.github/workflows/install_servers_ci.yaml b/.github/workflows/install_servers_ci.yaml
--- a/.github/workflows/install_servers_ci.yaml
+++ b/.github/workflows/install_servers_ci.yaml
@@ -10,135 +10,128 @@ jobs:
     steps:
       - name: get github code
         uses: actions/checkout@v4
-      
-      - name: Get Runner IP
-        id: get_ip
+
+      - name: Config AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: ${{ env.TF_VERSION}}
+
+      - name: Terraform init
+        run: terraform init
+        working-directory: infrastructure/terraform
+
+      - name: Terraform Format
+        run: terraform fmt
+        working-directory: infrastructure/terraform
+
+      - name: Terraform Validate
+        run: terraform validate
+        working-directory: infrastructure/terraform
+
+      - name: Terraform Plan
+        run: terraform plan -var-file="env.tfvars" -out=tfplan
+        working-directory: infrastructure/terraform
+
+      - name: Terraform apply
+        if: github.ref == 'refs/heads/master'
+        run: terraform apply -var-file="env.tfvars" -auto-approve tfplan
+        working-directory: infrastructure/terraform
+
+      - name: Get Private Key
+        id: read_file
         run: |
-          RUNNER_IP=$(curl -s https://api.ipify.org)
-          echo "RUNNER_IP=$RUNNER_IP" >> $GITHUB_ENV
-          echo "Runner IP is: $RUNNER_IP"
+          if [ -f infrastructure/terraform/la_clef_private.pem ]; then
+            FILE_CONTENT=$(base64 -w 0 infrastructure/terraform/la_clef_private.pem)
 
-      # - name: Config AWS Credentials
-      #   uses: aws-actions/configure-aws-credentials@v4
-      #   with:
-      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      #     aws-region: ${{ env.AWS_REGION }}
-
-      # - name: Set up Terraform
-      #   uses: hashicorp/setup-terraform@v3
-      #   with:
-      #     terraform_version: ${{ env.TF_VERSION}}
-
-      # - name: Terraform init
-      #   run: terraform init
-      #   working-directory: infrastructure/terraform
-
-      # - name: Terraform Format
-      #   run: terraform fmt
-      #   working-directory: infrastructure/terraform
-
-      # - name: Terraform Validate
-      #   run: terraform validate
-      #   working-directory: infrastructure/terraform
-
-      # - name: Terraform Plan
-      #   run: terraform plan -var-file="env.tfvars" -out=tfplan
-      #   working-directory: infrastructure/terraform
-
-      # - name: Terraform apply
-      #   if: github.ref == 'refs/heads/master'
-      #   run: terraform apply -var-file="env.tfvars" -auto-approve tfplan
-      #   working-directory: infrastructure/terraform
-
-      # - name: Get Private Key
-      #   id: read_file
-      #   run: |
-      #     if [ -f infrastructure/terraform/la_clef_private.pem ]; then
-      #       FILE_CONTENT=$(base64 -w 0 infrastructure/terraform/la_clef_private.pem)
-
-      #       # store data as Output
-      #       echo "$FILE_CONTENT"
-      #       echo file_content=$FILE_CONTENT >> $GITHUB_OUTPUT
-      #     else
-      #       echo "File not Found"
-      #       exit 0
-      #     fi
+            # store data as Output
+            echo "$FILE_CONTENT"
+            echo file_content=$FILE_CONTENT >> $GITHUB_OUTPUT
+          else
+            echo "File not Found"
+            exit 0
+          fi
       
-      # - name: Get DNS instance Jenkins and SonarQube
-      #   id: get_dns
-      #   run: |
-      #     FILE_DNS_JENKINS=$(cat infrastructure/terraform/dns_instance_jenkins.txt)
-      #     FILE_DNS_SONARQUBE=$(cat infrastructure/terraform/dns_instance_sonarqube.txt)
-      #     # Store data as Output
-      #     echo file_dns_jenkins=$FILE_DNS_JENKINS >> $GITHUB_OUTPUT
-      #     echo file_dns_sonarqube=$FILE_DNS_SONARQUBE >> $GITHUB_OUTPUT
+      - name: Get DNS instance Jenkins and SonarQube
+        id: get_dns
+        run: |
+          FILE_DNS_JENKINS=$(cat infrastructure/terraform/dns_instance_jenkins.txt)
+          FILE_DNS_SONARQUBE=$(cat infrastructure/terraform/dns_instance_sonarqube.txt)
+          # Store data as Output
+          echo file_dns_jenkins=$FILE_DNS_JENKINS >> $GITHUB_OUTPUT
+          echo file_dns_sonarqube=$FILE_DNS_SONARQUBE >> $GITHUB_OUTPUT
 
-      # - name: Add SSH Key to Github Secrets
-      #   env:
-      #     GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
-      #     SSH_KEY: ${{ steps.read_file.outputs.file_content }}
-      #   run: |
-      #     SSH_KEY=$(echo "$SSH_KEY" | base64 -d)
-      #     gh secret set SSH_PRIVATE_KEY --body "$SSH_KEY"
+      - name: Add SSH Key to Github Secrets
+        env:
+          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
+          SSH_KEY: ${{ steps.read_file.outputs.file_content }}
+        run: |
+          SSH_KEY=$(echo "$SSH_KEY" | base64 -d)
+          gh secret set SSH_PRIVATE_KEY --body "$SSH_KEY"
       
-      # - name: install Ansible and Dependencies
-      #   run: |
-      #     sudo apt-get update
-      #     sudo apt-get install -y ansible python3-pip
-      #     pip3 install boto3 botocore
+      - name: install Ansible and Dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y ansible python3-pip
+          pip3 install boto3 botocore
 
         
-      # - name: Setup SSH key Jenkins and SonarQube
-      #   env:
-      #     INSTANCE_DNS_JENKINS: ${{ steps.get_dns.outputs.file_dns_jenkins}}
-      #     INSTANCE_DNS_SONARQUBE: ${{ steps.get_dns.outputs.file_dns_sonarqube}}
-      #   run: |
-      #     eval `ssh-agent -s`
-      #     mkdir -p /home/runner/.ssh/
-      #     echo "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/key_ssh
-      #     chmod 700 /home/runner/.ssh/key_ssh
+      - name: Setup SSH key Jenkins and SonarQube
+        env:
+          INSTANCE_DNS_JENKINS: ${{ steps.get_dns.outputs.file_dns_jenkins}}
+          INSTANCE_DNS_SONARQUBE: ${{ steps.get_dns.outputs.file_dns_sonarqube}}
+        run: |
+          eval `ssh-agent -s`
+          mkdir -p /home/runner/.ssh/
+          echo "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/key_ssh
+          chmod 700 /home/runner/.ssh/key_ssh
           
-      #     # Verify key format
-      #     ssh-keygen -y -f /home/runner/.ssh/key_ssh || echo "Error Validation key"
+          # Verify key format
+          ssh-keygen -y -f /home/runner/.ssh/key_ssh || echo "Error Validation key"
 
-      #     # add key to SSH agent
-      #     ssh-add /home/runner/.ssh/key_ssh
+          # add key to SSH agent
+          ssh-add /home/runner/.ssh/key_ssh
 
-      #     # Add host key
-      #     ssh-keyscan -t rsa,dsa,ecdsa,ed25519 $INSTANCE_DNS_JENKINS >> /home/runner/.ssh/known_hosts
-      #     ssh-keyscan -t rsa,dsa,ecdsa,ed25519 $INSTANCE_DNS_SONARQUBE >> /home/runner/.ssh/known_hosts
+          # Add host key
+          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 $INSTANCE_DNS_JENKINS >> /home/runner/.ssh/known_hosts
+          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 $INSTANCE_DNS_SONARQUBE >> /home/runner/.ssh/known_hosts
       
-      # - name: Run Ansible Playbook
-      #   env:
-      #     INSTANCE_DNS_JENKINS: ${{ steps.get_dns.outputs.file_dns_jenkins}}
-      #     INSTANCE_DNS_SONARQUBE: ${{ steps.get_dns.outputs.file_dns_sonarqube}}
-      #     SSH_KKEY: ${{ secrets.SSH_PRIVATE_KEY }}
-      #   run: |
-      #     # chmod 400 infrastructure/terraform/la_clef_private.pem
-      #     echo "$SSH_KKEY" > /home/runner/my_key.pem
-      #     chmod 400 /home/runner/my_key.pem
+      - name: Run Ansible Playbook
+        env:
+          INSTANCE_DNS_JENKINS: ${{ steps.get_dns.outputs.file_dns_jenkins}}
+          INSTANCE_DNS_SONARQUBE: ${{ steps.get_dns.outputs.file_dns_sonarqube}}
+          SSH_KKEY: ${{ secrets.SSH_PRIVATE_KEY }}
+        run: |
+          # chmod 400 infrastructure/terraform/la_clef_private.pem
+          echo "$SSH_KKEY" > /home/runner/my_key.pem
+          chmod 400 /home/runner/my_key.pem
           
-      #     # Creation config SSH
-      #     echo "Config SSH"
-      #     echo -e "Host jenkins\n\t Hostname $INSTANCE_DNS_JENKINS\n\t User ubuntu\n\t IdentityFile /home/runner/my_key.pem\n" > /home/runner/.ssh/config
-      #     echo -e "Host sonarqube\n\t Hostname $INSTANCE_DNS_SONARQUBE\n\t User ubuntu\n\t IdentityFile /home/runner/my_key.pem\n" >> /home/runner/.ssh/config
-      #     cat /home/runner/.ssh/config
+          # Creation config SSH
+          echo "Config SSH"
+          echo -e "Host jenkins\n\t Hostname $INSTANCE_DNS_JENKINS\n\t User ubuntu\n\t IdentityFile /home/runner/my_key.pem\n" > /home/runner/.ssh/config
+          echo -e "Host sonarqube\n\t Hostname $INSTANCE_DNS_SONARQUBE\n\t User ubuntu\n\t IdentityFile /home/runner/my_key.pem\n" >> /home/runner/.ssh/config
+          cat /home/runner/.ssh/config
 
-      #     # Creation inventory
-      #     echo "Creation inventory"
-      #     echo -e "[jenkins]\njenkins\n" > infrastructure/ansible/inventory
-      #     echo -e "[sonarqube]\nsonarqube\n" >> infrastructure/ansible/inventory
-      #     cat infrastructure/ansible/inventory
+          # Creation inventory
+          echo "Creation inventory"
+          echo -e "[jenkins]\njenkins\n" > infrastructure/ansible/inventory
+          echo -e "[sonarqube]\nsonarqube\n" >> infrastructure/ansible/inventory
+          cat infrastructure/ansible/inventory
 
-      #     #Run ansible
-      #     echo "Run ansible"
-      #     echo "Install and Configure Jenkins"
-      #     ansible-playbook -i infrastructure/ansible/inventory infrastructure/ansible/configuration_jenkins.yaml
+          #Run ansible
+          echo "Run ansible"
+          echo "Install and Configure Jenkins"
+          ansible-playbook -i infrastructure/ansible/inventory infrastructure/ansible/configuration_jenkins.yaml
 
-      #     echo "Install Trivy on Jenkins Server"
-      #     ansible-playbook -i infrastructure/ansible/inventory infrastructure/ansible/install_trivy.yaml
+          echo "Install Trivy on Jenkins Server"
+          ansible-playbook -i infrastructure/ansible/inventory infrastructure/ansible/install_trivy.yaml
 
-      #     echo "Install and Configure SonarQube"
-      #     ansible-playbook -i infrastructure/ansible/inventory infrastructure/ansible/configuration_sonarqube.yaml
+          echo "Install and Configure SonarQube"
+          ansible-playbook -i infrastructure/ansible/inventory infrastructure/ansible/configuration_sonarqube.yaml
         
